FROM golang:1.18 as builder
ARG BUILD=now
ARG VERSION=dev
ARG REPO=repository
WORKDIR /src
COPY . /src

RUN make bin/frostfs-cli

# Executable image
FROM alpine AS frostfs-cli
RUN apk add --no-cache bash

WORKDIR /

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /src/bin/frostfs-cli /bin/frostfs-cli

CMD ["frostfs-cli"]
