FROM golang:1.18 as builder
ARG BUILD=now
ARG VERSION=dev
ARG REPO=repository
WORKDIR /src
COPY . /src

RUN make bin/frostfs-node

# Executable image
FROM alpine AS frostfs-node
RUN apk add --no-cache bash

WORKDIR /

COPY --from=builder /src/bin/frostfs-node /bin/frostfs-node

CMD ["frostfs-node"]
