FROM golang:1.17 as builder
ARG BUILD=now
ARG VERSION=dev
ARG REPO=repository
WORKDIR /src
COPY . /src

RUN make bin/frostfs-ir

# Executable image
FROM alpine AS frostfs-ir
RUN apk add --no-cache bash

WORKDIR /

COPY --from=builder /src/bin/frostfs-ir /bin/frostfs-ir

CMD ["frostfs-ir"]
